version: '3'
services:
  nginx:
    container_name: nginx
    image: my_nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp-websitefiles:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    image: my_mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp-database:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: my_wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp-websitefiles:/var/www/html
    restart: always


volumes: 
  wp-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pruangde/data/mariadb
  wp-websitefiles:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pruangde/data/wordpress

networks:
  inception:
    driver: bridge
